---
# Frontend Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: production
  labels:
    app: frontend
automountServiceAccountToken: false

---
# Backend Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: production
  labels:
    app: backend
automountServiceAccountToken: false

---
# Database Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: production
  labels:
    app: database
automountServiceAccountToken: false
