# Kubernetes etcd Encryption Configuration
# Enable encryption at rest for secrets in etcd
# Place this file at: /etc/kubernetes/enc/encryption-config.yaml

apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
    providers:
      # AES-CBC with 32-byte keys (recommended for production)
      - aescbc:
          keys:
            - name: key1
              secret: <BASE64_ENCODED_32_BYTE_KEY>
      # Identity provider for reading old unencrypted data during migration
      - identity: {}

# To generate a random 32-byte key:
# head -c 32 /dev/urandom | base64

# After creating this file:
# 1. Set proper permissions: chmod 600 /etc/kubernetes/enc/encryption-config.yaml
# 2. Add to kube-apiserver flags:
#    --encryption-provider-config=/etc/kubernetes/enc/encryption-config.yaml
# 3. Restart kube-apiserver
# 4. Encrypt existing secrets:
#    kubectl get secrets --all-namespaces -o json | kubectl replace -f -
